#note : in host you must run command : ln -s /data/volumes/jenkins_home /var/jenkins_home
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    user: root
    volumes:
      # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
      - /data/volumes/jenkins_home:/var/jenkins_home
      # mount docker sock and binary for docker in docker (only works on linux)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # uncomment for docker in docker
    privileged: true
    restart: always
    ports:
      - "49001:8080"
      - "50000:50000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 2048MB