# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  catiny-sonar:
    image: sonarqube:8.9.1-community
    volumes:
      - /data/volumes/sonarqube/data:/opt/sonarqube/data
      - /data/volumes/sonarqube/logs:/opt/sonarqube/logs
      - /data/volumes/sonarqube/extensions:/opt/sonarqube/extensions
    # Authentication is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete sonar.forceAuthentication variable or set sonar.forceAuthentication=true
    environment:
      - sonar.forceAuthentication=true
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "9001:9000"
